/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import DAO.Controlador;
import static gui.VentanaAbcc.res;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe
 */
public class VentanaClientes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaClientes
     */
    public VentanaClientes() {
        initComponents();
                try {
            CargarTabla();
            llenarcombo();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaAbcc.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
    }
        
        public void CargarTabla() throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) tablaView.getModel();
        modelo.setRowCount(0); 
        res = Controlador.buscarRegistro("Select * from views");
        try {
            while(res.next()){
                Vector v = new Vector();
                v.add(res.getInt(1));
                v.add(res.getString(2));
                v.add(res.getString(3));
                v.add(res.getString(4));
                modelo.addRow(v);
                tablaView.setModel(modelo);
                
            }
        } catch (SQLException e) {
            
            
        }
    }

                public void CargarTablaEspecifica(String clave) throws SQLException{
            DefaultTableModel modelo = (DefaultTableModel) tablaView.getModel();
           
        modelo.setRowCount(0);
        res = Controlador.buscarRegistro("Select * from views where clientNo like '%" + clave +"%' or propertyNo like '%" + clave +"%' or viewDate like '%" + clave +"%' or comment like '%" + clave +"%'");
        
        try {
            while(res.next()){
                Vector v = new Vector();
                v.add(res.getInt(1));
                v.add(res.getString(2));
                v.add(res.getString(3));
                v.add(res.getString(4));
                modelo.addRow(v);
                tablaView.setModel(modelo);
                
            }
        } catch (SQLException e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaView = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoProperty = new javax.swing.JTextField();
        campoCome = new javax.swing.JTextField();
        comboDia = new javax.swing.JComboBox<>();
        comboA = new javax.swing.JComboBox<>();
        comboMes = new javax.swing.JComboBox<>();
        comboClient = new javax.swing.JComboBox<>();
        comboPro = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "clientNo", "propertyNo", "viewDate", "comment"
            }
        ));
        tablaView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaView);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 450, 210));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 30));

        jLabel1.setText("Agregar");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 50, 40));

        jLabel2.setText("Editar");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 50, 40));

        jLabel3.setText("Eliminar");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 50, 40));
        getContentPane().add(campoProperty, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 80, -1));

        campoCome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoComeActionPerformed(evt);
            }
        });
        getContentPane().add(campoCome, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 140, 30));

        comboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(comboDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        comboA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        getContentPane().add(comboA, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(comboMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        comboClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClientActionPerformed(evt);
            }
        });
        getContentPane().add(comboClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 80, -1));

        comboPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DA", "OP", "FT", "AS" }));
        getContentPane().add(comboPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       
        if (! (campoProperty.getText().matches("[0-9]*"))  || campoProperty.getText().equals("") || ! (campoProperty.getText().length() == 5))  {
            JOptionPane.showMessageDialog(null, "Revisar propertyNo");
        }else if(campoCome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Revisar comment");
        }else {
            String fecha = comboDia.getSelectedItem().toString() + "/" + comboMes.getSelectedItem().toString() + "/" + comboA.getSelectedItem().toString();
            String prop = comboPro.getSelectedItem().toString() + campoProperty.getText();
            Controlador.insertarView(comboClient.getSelectedItem().toString(), prop, fecha, campoCome.getText());
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void campoComeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoComeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoComeActionPerformed

    private void comboClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboClientActionPerformed

    private void tablaViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaViewMouseClicked


        int acc = tablaView.rowAtPoint(evt.getPoint());
        System.out.println(String.valueOf(tablaView.getValueAt(acc, 0)));
        comboClient.setSelectedItem(String.valueOf(tablaView.getValueAt(acc, 0)));
        campoProperty.setText(String.valueOf(tablaView.getValueAt(acc, 1)).substring(2, 7));
        comboPro.setSelectedItem(String.valueOf(tablaView.getValueAt(acc, 1)).substring(0, 2));
        comboDia.setSelectedItem(String.valueOf(tablaView.getValueAt(acc, 2)).substring(0, 2));
        comboMes.setSelectedItem(String.valueOf(tablaView.getValueAt(acc, 2)).substring(3, 5));
        comboA.setSelectedItem(String.valueOf(tablaView.getValueAt(acc, 2)).substring(6, 8));
        campoCome.setText(String.valueOf(tablaView.getValueAt(acc, 3)));
        
    }//GEN-LAST:event_tablaViewMouseClicked

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

        try {
            CargarTablaEspecifica(jTextField1.getText());
        } catch (SQLException ex) {
            Logger.getLogger(VentanaAbcc.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        try {
           if (campoProperty.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Revisar propertyNo");
        }else if(campoCome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Revisar comment");
        }else {
            String fecha = comboDia.getSelectedItem().toString() + "/" + comboMes.getSelectedItem().toString() + "/" + comboA.getSelectedItem().toString();
            String prop = comboPro.getSelectedItem().toString() + campoProperty.getText();
            Controlador.editarView(comboClient.getSelectedItem().toString(),prop, fecha, campoCome.getText());
        } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Revisar información");
        }
        
        
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        try {
            String prop = comboPro.getSelectedItem().toString() + campoProperty.getText();
        Controlador.borrarView(prop);
        CargarTabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Revisar información");
        }
        
        
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaClientes().setVisible(true);
            }
        });
    }
    
    private void llenarcombo() throws SQLException{
        res = Controlador.buscarRegistro("Select clientNo from client");
        try {
            while(res.next()){
                comboClient.addItem(String.valueOf(res.getInt(1)));
                                
            }
            
        } catch (SQLException e) {
            
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoCome;
    private javax.swing.JTextField campoProperty;
    private javax.swing.JComboBox<String> comboA;
    private javax.swing.JComboBox<String> comboClient;
    private javax.swing.JComboBox<String> comboDia;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JComboBox<String> comboPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tablaView;
    // End of variables declaration//GEN-END:variables
}
